import sqlite3
import os

# 1. CONFIGURATION
DB_NAME = "studio.db"

def create_database():
    # --- SAFETY CHECK ---
    # If the database exists, we ask before deleting it so you don't lose work accidentally.
    if os.path.exists(DB_NAME):
        print(f"⚠️  '{DB_NAME}' already exists.")
        response = input("Do you want to delete it and start fresh? (y/n): ")
        if response.lower() != 'y':
            print("Operation cancelled. Existing database kept safe.")
            return
        os.remove(DB_NAME)

    # 2. CONNECT
    # This creates the file because we just deleted it (or it didn't exist)
    conn = sqlite3.connect(DB_NAME)
    cursor = conn.cursor()
    print(f"📂 Created database file: {DB_NAME}")

    # ==========================================
    # TABLE 1: PROJECTS (The Binders)
    # ==========================================
    cursor.execute('''
    CREATE TABLE projects (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        description TEXT,
        aspect_ratio TEXT DEFAULT '16:9',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
    ''')
    print("✅ Table 'projects' created.")

    # ==========================================
    # TABLE 2: ASSETS (The Raw Materials)
    # Cast members, Locations, Props generated by Flux
    # ==========================================
    cursor.execute('''
    CREATE TABLE assets (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        project_id INTEGER NOT NULL,
        type TEXT NOT NULL,         -- 'cast', 'loc', 'prop'
        name TEXT NOT NULL,
        prompt TEXT,
        image_path TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
    )
    ''')
    print("✅ Table 'assets' created.")

    # ==========================================
    # TABLE 3: SCENES (The Timeline Containers)
    # Grouping shots together (e.g., "Scene 1: The Alleyway")
    # ==========================================
    cursor.execute('''
    CREATE TABLE scenes (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        project_id INTEGER NOT NULL,
        name TEXT,
        order_index INTEGER DEFAULT 0, -- To sort Scene 1, Scene 2, etc.
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
    )
    ''')
    print("✅ Table 'scenes' created.")

    # ==========================================
    # TABLE 4: SHOTS (The Action)
    # Specific camera takes linked to a Scene
    # ==========================================
    cursor.execute('''
    CREATE TABLE shots (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        scene_id INTEGER NOT NULL,
        
        -- The instruction for the AI
        prompt TEXT,
        
        -- Consistency: Which Asset (Actor/Loc) is in this shot?
        reference_asset_id INTEGER,
        
        -- The Files
        keyframe_url TEXT,  -- The static image (Stage 1: Flux)
        video_url TEXT,     -- The video clip (Stage 2: Wan 2.1)
        
        -- Status tracking
        status TEXT DEFAULT 'pending', -- 'pending', 'generating_keyframe', 'ready_for_video', 'generating_video', 'complete'
        
        order_index INTEGER DEFAULT 0,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        
        FOREIGN KEY (scene_id) REFERENCES scenes (id) ON DELETE CASCADE,
        FOREIGN KEY (reference_asset_id) REFERENCES assets (id)
    )
    ''')
    print("✅ Table 'shots' created.")

    # ==========================================
    # DUMMY DATA (For Testing)
    # ==========================================
    print("📝 Adding sample data...")
    
    # 1. Create a Project
    cursor.execute("INSERT INTO projects (name, description, aspect_ratio) VALUES (?, ?, ?)", 
                   ("Sci-Fi Short Film", "A cyberpunk detective story.", "2.39:1"))
    project_id = cursor.lastrowid

    # 2. Create an Asset (The Hero)
    cursor.execute('''
        INSERT INTO assets (project_id, type, name, prompt, image_path)
        VALUES (?, ?, ?, ?, ?)
    ''', (project_id, "cast", "Detective Miller", "Gritty detective in rain", "/placeholder_cast.jpg"))
    asset_id = cursor.lastrowid

    # 3. Create a Scene
    cursor.execute("INSERT INTO scenes (project_id, name, order_index) VALUES (?, ?, ?)",
                   (project_id, "Scene 1: The Discovery", 1))
    scene_id = cursor.lastrowid

    # 4. Create a Shot (linked to the Asset)
    cursor.execute('''
        INSERT INTO shots (scene_id, prompt, reference_asset_id, status, order_index)
        VALUES (?, ?, ?, ?, ?)
    ''', (scene_id, "Wide shot of Miller walking towards the neon sign", asset_id, "pending", 1))

    # SAVE AND CLOSE
    conn.commit()
    conn.close()
    print("🎉 Database setup complete! You are ready for Method B.")

if __name__ == "__main__":
    create_database()